/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-18 13:36:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"row mt-5 pt-3\">\r\n");
      out.write("	<div class=\"col-xl-6 col-lg-12 mb-4\">\r\n");
      out.write("		<div class=\"tm-bg-gray p-5 h-100\">\r\n");
      out.write("			<h3 class=\"tm-text-primary mb-3\">Do you want to get our latest\r\n");
      out.write("				updates?</h3>\r\n");
      out.write("			<p class=\"mb-5\">Please subscribe our newsletter for upcoming new\r\n");
      out.write("				videos and latest information about our work. Thank you.</p>\r\n");
      out.write("			<form action=\"\" method=\"GET\" class=\"tm-subscribe-form\">\r\n");
      out.write("				<input type=\"text\" name=\"email\" placeholder=\"Your Email...\" required>\r\n");
      out.write("				<button type=\"submit\" class=\"btn rounded-0 btn-primary tm-btn-small\">Subscribe</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-6 col-12 mb-4\">\r\n");
      out.write("		<div class=\"p-5 tm-bg-gray\">\r\n");
      out.write("			<h3 class=\"tm-text-primary mb-4\">Quick Links</h3>\r\n");
      out.write("			<ul class=\"list-unstyled tm-footer-links\">\r\n");
      out.write("				<li><a href=\"#\">Duis bibendum</a></li>\r\n");
      out.write("				<li><a href=\"#\">Purus non dignissim</a></li>\r\n");
      out.write("				<li><a href=\"#\">Sapien metus gravida</a></li>\r\n");
      out.write("				<li><a href=\"#\">Eget consequat</a></li>\r\n");
      out.write("				<li><a href=\"#\">Praesent eu pulvinar</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"col-xl-3 col-lg-6 col-md-6 col-sm-6 col-12 mb-4\">\r\n");
      out.write("		<div class=\"p-5 tm-bg-gray h-100\">\r\n");
      out.write("			<h3 class=\"tm-text-primary mb-4\">Our Pages</h3>\r\n");
      out.write("			<ul class=\"list-unstyled tm-footer-links\">\r\n");
      out.write("				<li><a href=\"#\">Our Videos</a></li>\r\n");
      out.write("				<li><a href=\"#\">License Terms</a></li>\r\n");
      out.write("				<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("				<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("				<li><a href=\"#\">Privacy Policies</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- row -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"row pt-5\">\r\n");
      out.write("	<div class=\"col-12\">\r\n");
      out.write("		<p class=\"text-right\">\r\n");
      out.write("			Copyright 2020 The Video Catalog Company - Designed by <a\r\n");
      out.write("				href=\"https://templatemo.com\" rel=\"nofollow\" target=\"_parent\">TemplateMo</a>\r\n");
      out.write("		</p>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
